### ISSUE TITLE
Addresses / payment requests generation

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#314]
#### User story
- _As a Witnet user, I want Sheikah to generate addresses where other Witnet users can send me wit tokens in such a way that I can spend those tokens afterwards._
- _As a Witnet user, I'd love Sheikah to generate QR codes for my addresses so that I can share them more easily and without having to care about copying them correctly._
- _As a Witnet user, I would appreciate if Sheikah listed a history of my past addresses or payment requests._

#### Actionables
- [x] Standardize [Witnet's P2PKH address format][addresses]
- [x] Create library code for [derivating P2PKH addresses from keys]
- [ ] Implement a `generateAddress` API handler. This won't actually just generate an address but generate new final keys and derive the address from them. (Issue #391)
- [ ] Create a renderer-side `generateAddress` API client method. (Issue #392)
- [ ] Create the address generation UI component (sketch is at #16) and make it consume the `generateAddress` API client method.
- [ ] Create the addresses / payment requests history component.

[addresses]: https://github.com/aesedepece/WIPs/blob/wip-adansdpc-addresses/wip-adansdpc-addresses.md
[derivation]: https://github.com/witnet/sheikah/blob/master/app/main/crypto/address/p2pkh.ts#L28

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
