### ISSUE TITLE
App sidebar UI polish

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#345]
#### Motivation
The app sidebar needs some final polish to make it look like depicted in issue #16.

#### Tasks
_Someone tackling this issue shall:_
- [x] Take a look at issue #16. Precise measures can also be taken from the sketch SVG (available in our KeyBase team folder)
- [x] Remove underline (CSS `font-decoration`) from links.
- [x] Adjust font sizes
- [x] Adjust font weight
- [x] Adjust font color (both for neutral and selected states)
- [x] Make sure the account switcher and the thick line on the left of the selected section match the exact shade of blue from the sketch.
- [x] Make sure that all the icons in the section links actually make sense. 
- [x] Double check sizing and spacing of the labels and icons in the section links
- [x] Double check thickness of the selected section blue indicator
- [x] Replace the "mainnet" indicator at the bottom for "prototype" and a yellow dot indicator (see #344)
- [x] Make the line above the "mainnet" indicator not span the entire horizontal space but to have blank areas on both sides of it.
