### ISSUE TITLE
Remaining UI/UX improvements

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#435]
- [x] App settings should trigger "unimplemented" toast. #440 
- [x] Sidebar should be narrower #441 
- [x] Logo looks poor #441 
- [x] Sidebar button spacing between elements (icons, labels) is wrong #441 
- [x] Sidebar font is too bold #441 
- [x] Unconfirmed indicators should be yellow. #429
- [x] Transaction list dates should be printed in human readable format #441 
- [x] Font is to small across main screen (increase to 16px) #441
- [x] Settings and synced area in the bottom part of the sidebar #441 
- [x] Values of transactions should be bolder #441 
- [x] Tab selectors are not styled properly #441 
- [x] Sections and tabs should be highlighted when selected #441
- [x] "Wallet > Transaction" tab should be selected by default #441 
- [x] Right side blocks should have a bigger bottom margin (balances, vesting graph, etc.) #441 
- [x] Right side blocks titles should be bolder #441 
- [x] Cards are not dropping shadows right now #441 
- [x] Sidebar is not dropping shadow right now #441 
- [x] Make send screen amount button look like the one in the receive screen
- [x] Turn the Fee field in the send screen into a selection box with "High/Medium/Low" values #441 

##### Leftovers
- [x] #343: Implement listcards with empty states Closed by #429
- [x] #371: Improve copy for "Passwords must match"

##### Low priorities
- [ ] Giving numbers to prefilled wallets
- [ ] Distinguishing wallet unlock buttons from the create/import recover wallet
- [ ] Think about putting pending and confirmed transactions into a single list
- [ ] Question if timelocks should be shown in the main screen
- [x] Thinks about "Addresses" vs. "Payment Request"

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
